### ISSUE TITLE
Secure Mask On Password Textbox

### ISSUE THREAD

**Issue by btull89** [lucasalexander/AlexanderDevelopment.ConfigDataMover#1]
The password textbox is plain text. I don't feel comfortable typing my secure password with coworkers nearby. Can you put a password mask on it?

**Comment by lucasalexander** [comment]
I considered this, however the password is not masked in the connection string field on the main form, and it is stored as plain text if the connection information is saved, so I didn't see the point in masking it. I may revisit this at some point in the future.

**Comment by btull89** [comment]
Would you like me to try encrypting the passwords everywhere and submit a pull request?

**Comment by lucasalexander** [comment]
Yes, that would be great! There are a few constraints to keep in mind:
1. The GUI should be able to open and execute a previously saved import job. Saving the job would then encrypt the password.
2. The CLI version should be able to execute an import job saved with encrypted or plain-text passwords.
3. In a saved job, only the password should be encrypted. The server and username should be readable as plain text.

Then I can (or you if you prefer) can update the GUI interface so that the entire connection string is not displayed or editable on the main form.

**Comment by btull89** [comment]
Thank you for supplying me with constraints.
I'll see what I can do, but don't hold your breath.

I will mainly work on this during my lunch break if I'm motivated.

**Comment by lucasalexander** [comment]
Sure thing. I appreciate your interest in the project!

**Comment by lucasalexander** [comment]
Updated in v1.7.0.1 release
