### ISSUE TITLE
Use of GUID mappings

### ISSUE THREAD

**Issue by SeanKe11y** [lucasalexander/AlexanderDevelopment.ConfigDataMover#10]
Hi Alexander,

I am trying to use your tool to migrate Products from one instance to another. I am running into an issue with moving the Price List Item (productpricelevel) records, due to the fact that the Unit (uom) records are different in each instance.

Sounds like GUID mapping is what I need.

In the screenshots I've seen it looks like you can include a source and target GUID in different columns (see here: https://community.dynamics.com/crm/b/alexanderdevelopment/archive/2015/11/11/introducing-the-alexander-development-dynamics-crm-configuration-data-mover). But in the application I'm using (Version 2.4.6587.18905) I just see a text box, see attached screenshot.

![configdatamoverguidmapping](https://user-images.githubusercontent.com/7339976/39808729-a785044c-5377-11e8-8912-bca5ec958c4b.PNG)

I'm wondering how I can include the GUID mappings to get this to work for me? I've tried a few different things but nothing works so far.

Thanks,
Sean

**Comment by lucasalexander** [comment]
I updated the way GUID mappings are handled in version 2 in order to simplify the user experience. https://alexanderdevelopment.net/post/2017/02/04/dynamics-365-configuration-data-mover-v2-0/

Now you just put the source GUID and the target GUID on the same line separated by a "->" like shown in this screenshot.
![GUID mappings](https://user-images.githubusercontent.com/95673/39817439-c3c4c5ca-5363-11e8-8891-45b51e2bc7d6.png)

**Comment by SeanKe11y** [comment]
Hi Lucas, thanks, that worked.

Regards,
Sean
